/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/custom-button.vue')['default']
    CardGrid: typeof import('./src/components/NaviCardGrid.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CostomButton: typeof import('./src/components/custom-button.vue')['default']
    CustomButton: typeof import('./src/components/custom-button.vue')['default']
    DemoCeremony: typeof import('./src/components/demo-ceremony.vue')['default']
    DynamicGrid: typeof import('./src/components/DynamicGrid.vue')['default']
    DynamicGrid2: typeof import('./src/components/DynamicGrid-2.vue')['default']
    DynamicGrid3: typeof import('./src/components/DynamicGrid-3.vue')['default']
    DynamicGrid4: typeof import('./src/components/DynamicGrid-4.vue')['default']
    DynamicGridDemo: typeof import('./src/components/DynamicGrid-demo.vue')['default']
    EleNavBar: typeof import('./src/components/EleNavBar.vue')['default']
    Footer: typeof import('./src/components/NaviFooter.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NaviCardGrid: typeof import('./src/components/NaviCardGrid.vue')['default']
    NaviFooter: typeof import('./src/components/NaviFooter.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VedioView: typeof import('./src/components/video-view.vue')['default']
    VideoView: typeof import('./src/components/video-view.vue')['default']
  }
}
