/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/page': RouteRecordInfo<'/page', '/page', Record<never, never>, Record<never, never>>,
    '/project/[id]': RouteRecordInfo<'/project/[id]', '/project/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/talk': RouteRecordInfo<'/talk', '/talk', Record<never, never>, Record<never, never>>,
    '/text-page-1': RouteRecordInfo<'/text-page-1', '/text-page-1', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/user/addProject': RouteRecordInfo<'/user/addProject', '/user/addProject', Record<never, never>, Record<never, never>>,
    '/user/editProject': RouteRecordInfo<'/user/editProject', '/user/editProject', Record<never, never>, Record<never, never>>,
    '/user/editProject-odd': RouteRecordInfo<'/user/editProject-odd', '/user/editProject-odd', Record<never, never>, Record<never, never>>,
  }
}
